spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:5432/keep_up
    username: muse
    password: muse

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      format_sql: true
    database: postgresql

application:
  security:
    jwt:
      secret-key: sfrvdvrgrvdvdv
      expiration: 8640000